### ISSUE TITLE
feat: cd - to go to previous dir

### ISSUE THREAD

**Issue by TorchedSammy** [Mewyuna/Hilbish#53]
`cd -` should use the $OLDPWD env variable to cd to the old directory
how this should be handled is either:
1. `fs.cd()` should store the old pwd to that env variable, then actually change the directory. then we check in lua if `arg == '-'`, and if it is then  `fs.cd(os.getenv 'OLDPWD')`
2. the other case being the function itself handles changing to old pwd if `fs.cd '-'` is used

relevant files to change are:
in case 1, `golibs/fs/fs.go` and `preload.lua`
in case 2 only ^

**Comment by devins2518** [comment]
stupid github wont close this through a commit
